/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'account', { get: function () { return require('./account'); } });
Object.defineProperty(exports, 'accountLdap', { get: function () { return require('./account-ldap'); } });
Object.defineProperty(exports, 'accountOidc', { get: function () { return require('./account-oidc'); } });
Object.defineProperty(exports, 'accountPassword', { get: function () { return require('./account-password'); } });
Object.defineProperty(exports, 'authMethod', { get: function () { return require('./auth-method'); } });
Object.defineProperty(exports, 'authMethodLdap', { get: function () { return require('./auth-method-ldap'); } });
Object.defineProperty(exports, 'authMethodOidc', { get: function () { return require('./auth-method-oidc'); } });
Object.defineProperty(exports, 'authMethodPassword', { get: function () { return require('./auth-method-password'); } });
Object.defineProperty(exports, 'credentialJson', { get: function () { return require('./credential-json'); } });
Object.defineProperty(exports, 'credentialLibraryVault', { get: function () { return require('./credential-library-vault'); } });
Object.defineProperty(exports, 'credentialLibraryVaultSshCertificate', { get: function () { return require('./credential-library-vault-ssh-certificate'); } });
Object.defineProperty(exports, 'credentialSshPrivateKey', { get: function () { return require('./credential-ssh-private-key'); } });
Object.defineProperty(exports, 'credentialStoreStatic', { get: function () { return require('./credential-store-static'); } });
Object.defineProperty(exports, 'credentialStoreVault', { get: function () { return require('./credential-store-vault'); } });
Object.defineProperty(exports, 'credentialUsernamePassword', { get: function () { return require('./credential-username-password'); } });
Object.defineProperty(exports, 'group', { get: function () { return require('./group'); } });
Object.defineProperty(exports, 'host', { get: function () { return require('./host'); } });
Object.defineProperty(exports, 'hostCatalog', { get: function () { return require('./host-catalog'); } });
Object.defineProperty(exports, 'hostCatalogPlugin', { get: function () { return require('./host-catalog-plugin'); } });
Object.defineProperty(exports, 'hostCatalogStatic', { get: function () { return require('./host-catalog-static'); } });
Object.defineProperty(exports, 'hostSet', { get: function () { return require('./host-set'); } });
Object.defineProperty(exports, 'hostSetPlugin', { get: function () { return require('./host-set-plugin'); } });
Object.defineProperty(exports, 'hostSetStatic', { get: function () { return require('./host-set-static'); } });
Object.defineProperty(exports, 'hostStatic', { get: function () { return require('./host-static'); } });
Object.defineProperty(exports, 'managedGroup', { get: function () { return require('./managed-group'); } });
Object.defineProperty(exports, 'managedGroupLdap', { get: function () { return require('./managed-group-ldap'); } });
Object.defineProperty(exports, 'role', { get: function () { return require('./role'); } });
Object.defineProperty(exports, 'scope', { get: function () { return require('./scope'); } });
Object.defineProperty(exports, 'storageBucket', { get: function () { return require('./storage-bucket'); } });
Object.defineProperty(exports, 'target', { get: function () { return require('./target'); } });
Object.defineProperty(exports, 'user', { get: function () { return require('./user'); } });
Object.defineProperty(exports, 'worker', { get: function () { return require('./worker'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

